### ISSUE TITLE
Convert to proper pyhton source structure

### ISSUE THREAD

**Issue by tmbo** [scalableminds/webknossos-cuber#1]
There should be a src directory called e.g. `webknossos-cuber` containing all the source packages. Furthermore there should be a `setup.py`(https://github.com/golastmile/rasa_nlu/blob/master/setup.py) and a `requirements.txt`.

**Comment by normanrz** [comment]
I improved the structure. 
@tmbo Can you please review?

**Comment by tmbo** [comment]
looks good :+1: can successfully open it in intellij and everything seems fine.

Nevertheless, I would avoid the current naming
- the repository should rather be `webknossos-cuber`
- the package should rather be `wkcuber` (as underscores in python packages are discouraged)

I think we should change that now, since now it is still easy to do so.

**Comment by normanrz** [comment]
Do you think it is a good idea to diverge repo and package name?

**Comment by tmbo** [comment]
that is a good point, they should probably be the same

**Comment by normanrz** [comment]
I went for `webknossos-cuber` and `wkcuber`, because I'd like to keep the repo names consistent and `wkcuber` seems more fitting in the python world. Other projects also have the name split (e.g. `scikit-learn` and `sklearn`).
