### ISSUE TITLE
Cubing 16-bit tiffs without providing --dtype simply crops that data

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos-cuber#177]
I suggest that the dtype should simply be inferred from the src image. So, if the input data is in 16 bit, than the dtype defaults to 16 bit.

Do you agree, @normanrz?

**Comment by normanrz** [comment]
Now that wk supports most datatypes, this makes sense

**Comment by jstriebel** [comment]
@philippotto Is this important, something for the near future, or rather in the backlog?

**Comment by philippotto** [comment]
Somewhere between "important" and "something for the near future" I'd say :) The plan is to use wkcuber directly from within webknossos when users import their tiffs. if they import 16-bit tiffs, the conversion will produce wrong output currently. So, we should definitely tackle this and also I think it's not a big deal.

**Comment by fm3** [comment]
I just checked PR #268 and it already includes this :)
