### ISSUE TITLE
Add support for 16-bit image data

### ISSUE THREAD

**Issue by amotta** [scalableminds/webknossos-cuber#18]
Add support for 16-bit image data

**Comment by normanrz** [comment]
Which command do you mean? For most commands you can use `--dtype uint16`

**Comment by amotta** [comment]
Hi Norman! Welcome back :)

I've just talked to / tried webKNOSSOS with another scientist at the MPIBR who is working with light microscopic data. While trying to prepare his data for webKNOSSOS I've realized that we're not properly handling 16-bit images yet.

If I'm not mistaken, webKNOSSOS only supports 8-bit "color" data. This means that cubing 16-bit image should probably notify the user and perform an additional conversion step.

**Comment by normanrz** [comment]
Ah, I see. How would 16-Bit data be interpreted? webKnossos hast multi-channel and rgb support.

**Comment by amotta** [comment]
Oh. In this case it's really just single-channel gray-scale data where the range from black to white is mapped onto [0, 2^16[ instead of [0, 2^8[.

I'm not saying that webKNOSSOS needs to support this kind of data. But it might be helpful if the cuber were able to convert 16-bit to 8-bit (e.g., by uint8(round(double(inputData) / 256))).

**Comment by normanrz** [comment]
When you use the `--dtype uint8` flag, you should already get `uint8(min(255, inputData))`. Not sure if dividing by 256 would make sematically more sense.

**Comment by philippotto** [comment]
Since webKnossos supports 16 bit data by now, this issue can be closed.
