### ISSUE TITLE
High-level API: Support for mags e.g. 2-2-2

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos-cuber#204]
`WKDataset` requires mag folders to use the simple notation (e.g `2`) for uniform mags. However, `2-2-2` would also be a valid folder name.
Code ref here: https://github.com/scalableminds/webknossos-cuber/blob/master/wkcuber/api/Layer.py#L110

**Comment by normanrz** [comment]
Also, a better error message for missing mags would be nice :-D

**Comment by philippotto** [comment]
See #220.
