### ISSUE TITLE
Exporting wkw to tiff in another mag uses wrong bounding box

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos-cuber#228]
The bounding box of mag 1 is used instead of the specified mag.

**Comment by jstriebel** [comment]
@philippotto Is this still an issue? How can this be reproduced?

**Comment by philippotto** [comment]
I think I used `export_wkw_as_tiff.py` to export some wkw to tiff and passed a mag which was not mag 1. Then, the bounding box wasn't properly calculated. But looking at the code shows that this should be taken care of (at least `export_tiff_slice` divides the bbox by the mag).

I'll close it and we can re-open when necessary.
