### ISSUE TITLE
High-level API cannot interpret multi-channel data ("uint24")

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos-cuber#235]
```data type "uint24" not understood``` is thrown when an RGB layer should be opened.

**Comment by philippotto** [comment]
In the past, datasource-properties.json contained "uint24" for three-channel layers. However, the new API probably would expect uint8 (since one channel consists of 8 bit). Not sure how we want to unify this..

**Comment by daniel-wer** [comment]
This affects voxelytics quite a bit as most connect datasets contain a uint24 prediction layer. Those datasets cannot be opened by the high-level API.
