### ISSUE TITLE
Support for RGB TIFF files

### ISSUE THREAD

**Issue by youri-k** [scalableminds/webknossos-cuber#283]
The `TiffFile` library seems to differentiate between standard channel count (denoted as `C`) and a different channel count for rgb files (denoted as `S`). We should support both formats and possibly use the `C` count as a hint for different layers for wK.

**Comment by fm3** [comment]
Turns out the old version of the cuber didn’t support this case either (though it had a slightly prettier error message). So It’s not a regression. It would still be a useful feature, so let’s keep the Issue
