### ISSUE TITLE
Add compress function to high-level API

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos-cuber#288]
I think one of the last missing core functions of the high-level API is the ability to compress a mag-layer, and maybe even to write to compressed layers.

**Comment by rschwanhold** [comment]
Writing to compressed layers is already supported for `WKDataset` (`https://github.com/scalableminds/webknossos-cuber/blob/master/wkcuber/api/MagDataset.py`). The `write` function has the parameter `allow_compressed_write`. In that case the necessary data is read to pad the data. This is not necessary if the data is already aligned with the boundingboxes of the files on disk.

**Comment by normanrz** [comment]
That sounds great!

I think what I was looking for is a method to compress an existing mag-layer in-place similar to https://github.com/scalableminds/webknossos-cuber/blob/master/wkcuber/compress.py with an API like
```python
mag1 = ds.get_layer("color").get_mag("1")
# mag1 is uncompressed

mag1.compress()
# mag1 is compressed now

mag1.read(...)
```
