### ISSUE TITLE
float/double instead of float32/float64 in WKDataset

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos-cuber#299]
webknossos expects the datatypes to be called `float` and `double` instead of `float32` or `float64` in the datasource-properties.json.

See https://github.com/scalableminds/webknossos-cuber/issues/100

**Comment by rschwanhold** [comment]
If a color layer has 3 channel and `uint8` as the dtype (`dtype_per_channel`) then `uint24` is stored in the `datasource-properties.json`. How does this translate to floating points? 
Lets say I have a layer with 1 channel and I specify the dtype to be `float`: So then the `datasource-properties.json` should contain `float`, right? But what if the layer has 3 channel (should it then be `float96` or just `float`)?

**Comment by normanrz** [comment]
wk only supports a subset of the what wkw could support. Multi-channel floats are not supported. See https://github.com/scalableminds/webknossos/blob/5777d8334386bd3716db8024beee9da36c861962/webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/datasource/DataLayer.scala#L30-L42
