### ISSUE TITLE
Convenience for wkcuber.api

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos-cuber#301]
To open/create a dataset with the cool new high-level API the following code is required:

```python
from wkcuber.api.Dataset import WKDataset
from pathlib import Path

ds1 = WKDataset.create(Path("path") / "to" / "dataset1", scale=(128,128,128))
ds2 = WKDataset.open(Path("path") / "to" / "dataset2")

```

For one-off scripts, I think that could be a bit more convenient, if we had an API like this

```python
from wkcuber import WKDataset

ds1 = WKDataset.create("path/to/dataset1", scale=(128, 128, 128))
ds2 = WKDataset.open("path/to/dataset2")
```

Any thoughts? @rschwanhold @jstriebel @philippotto

**Comment by normanrz** [comment]
Context: I have been using the API a couple of times now to convert datasets for users, where the automatic conversion didn't succeed yet.

**Comment by jstriebel** [comment]
Sounds fair for me. For public-facing apis, that are not only used in vx or other internal code, allowing `Union[Path, str]` makes sense.

**Comment by philippotto** [comment]
Yes, fully agree :+1:

**Comment by rschwanhold** [comment]
Is this limited to the Dataset API or are there more cases like this?

**Comment by normanrz** [comment]
I think `WKDataset` is the primary entry point for the API, so there would be the biggest benefit. I don't think we need to expose the whole API in this manner.

**Comment by normanrz** [comment]
My initial request also contained re-exporting `WKDataset` under `wkcuber`:

```python
from wkcuber import WKDataset
```
