### ISSUE TITLE
Cuber does not set bounding box correctly

### ISSUE THREAD

**Issue by georgwiese** [scalableminds/webknossos-cuber#31]
When cubing an image stack, the cuber rounds up to full 1024^3 cubes and pads with zeros. That leads to black slices at the end of the dataset and black areas at the right and bottom of each slice.

The cuber should set the bounding box property correctly in the `datasource-properties.json` such that the padding voxels are not included in the bounding box.

**Comment by philippotto** [comment]
Not sure, if this issue still persists, but you could have a look at investigating this, @MartinBuessemeyer :)

**Comment by MartinBuessemeyer** [comment]
I simply run the tests which includes tiff cubing and found out that the bounding box is set correctly. Thus this issue does no longer exist. :muscle:
