### ISSUE TITLE
Bounding box in JSON after conversion

### ISSUE THREAD

**Issue by cnzqy1** [scalableminds/webknossos-cuber#310]
Starting from v0.5.0 the bounding box specified in the JSON is no longer the exact dimensions of the source TIFF image stack. If convert using just `python -m wkcuber`, then the xyz dimensions of the bounding box are all set to `1024`. If convert using `python -m wkcuber.convert_image_stack_to_wkw`, then the xyz dimensions of the bounding box are slightly larger than the source stack dimensions. Converting using v0.4.0 gives the correct bounding box dimensions.

**Comment by youri-k** [comment]
@cnzqy1 could you provide me some sample files to debug the problem. The initial problem of the `python -m wkcuber` interface always using `1024` as xyz dimensions should be fixed by now, but that does not explain the differing dimensions when using the `python -m wkcuber.convert_image_stack_to_wkw` entry point.

**Comment by cnzqy1** [comment]
Test volume and wkcuber conversion results: https://drive.google.com/file/d/13nI2D3xZznFrMHp4HQf5kCxykTSbBMhS/view?usp=sharing

Expected bounding box: 465, 443, 61. Actual bounding box: 472, 448, 64 (same for both entry points).

Probably because bounding boxes generated in the new versions are aligned to the block size? v0.4.0 and earlier versions yield the correct bounding boxes.

New entry point conversion command (`auto`): `python -m wkcuber --scale 6,6,6 --name cube7 cube7/ auto/`
Old entry point conversion command (`legacy`): `python -m wkcuber.convert_image_stack_to_wkw --layer_name color --name cube7 cube7/ legacy/`

**Comment by youri-k** [comment]
Thank you very much for the provided sample data. I was able to find the culprit in the downsampling code. The next release `v0.6.6` should persist the correct bounding box.

**Comment by youri-k** [comment]
I just released `v0.6.6`. Please check if everything works for you, too.

**Comment by cnzqy1** [comment]
Yes, it's working properly now. Thanks!
