### ISSUE TITLE
Auto-detect largest segment id (for small datasets)

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos-cuber#341]
When adding segments to an existing segmentation (e.g. in a volume annotation) the largest existing segment ID is required so that nothing gets overwritten.
Currently, the user has to specify it manually (in webKnossos or possibly in the cuber as well?)
It would be helpful to just go through the entire dataset during cubing and determine the correct largest segment ID.
Since this may take a while for large datasets, maybe this feature would be enabled for small datasets only (e.g. <1GB).

**Comment by rschwanhold** [comment]
Yes, the `largest_segment_id` has to be specified in the dataset API when creating a segmentation layer.

Do you mean something like `detect_segmentation_layer` from `metadata.py` (https://github.com/scalableminds/webknossos-cuber/blob/master/wkcuber/metadata.py)?

**Comment by fm3** [comment]
Yes, that looks like what I need :) Is there a way to trigger that from the command-line? (I’m using the wkcuber command, which does the auto-detection cubing)

**Comment by rschwanhold** [comment]
Do you want an explicit command to lookup the `largest_segment_id` or are you asking for a way to use this while cubing?

If the later is the case, then we should call `write_webknossos_metadata` (which calls `detect_segmentation_layer`) after cubing. 

If you are looking for a quick fix:
Maybe `convert_image_stack_to_wkw.py` (cubing + metadata + downsampling) might work for you.

**Comment by fm3** [comment]
Good question. From a higher-level perspective, I’m working on the task that lets users upload arbitrary data to webKnossos.org, which then converts whatever it gets to wkw. When users upload segmentations (in basically arbitrary format), it would be nice if the converted dataset had the correct largest_segment_id set already in its properties.
However, that does not _have_ to mean the cubing call does it automatically. We can also call other cuber methods after `python -m wkcuber` has finished.
Would you recommmend that instead of including more arguments for the wkcuber entry point?

**Comment by rschwanhold** [comment]
I just realized that I was wrong. There is already an command line interface for this: `python -m wkcuber.metadata <path> <name> --compute_max_id`

This either creates the properties file or refreshes it (depending on the arguments).

**Comment by fm3** [comment]
Ah, yes thank you, I missed that as well. I think that will do the trick for me, thanks for your help!
