### ISSUE TITLE
Add reusable BufferedWriter

### ISSUE THREAD

**Issue by georgwiese** [scalableminds/webknossos-cuber#68]
Similar to what is implemented in alignment tools

**Comment by MartinBuessemeyer** [comment]
AlignmentTools: BufferedSliceWriter, move to wkcuber

after the PR is merged. go to segmentation tools and remove from alignment tools and import it.

**Comment by philippotto** [comment]
> after the PR is merged. go to segmentation tools and remove from alignment tools and import it.

@MartinBuessemeyer the second part is actionable now, I think :)

**Comment by philippotto** [comment]
@normanrz The BufferedSliceWriter wasn't removed from the segmentation tools, yet. Also, I think the implementations have diverged in the mean time. Not sure whether we want to pick this up again or whether we want to unify it at a later point.

**Comment by normanrz** [comment]
I think it would be good to unify both implementations and only use the one in this repo.
