### ISSUE TITLE
Refactor lib interface for (anisotropic) downsampling

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos-cuber#92]
Right now, the anisotropic downsampling is easy to use when invoked via the CLI. However, when using wkcuber as a library, the difference between anisotropic and isotropic downsampling is a bit cumbersome. Ideally, I'd like it to be a simple flag like this:

`downsample(path, max_mag,..., anisotropic=True)`

Also, the scale should be derived by the path automatically so that the call side doesn't have to look this up.

**Comment by MartinBuessemeyer** [comment]
`Also, the scale should be derived by the path automatically so that the call side doesn't have to look this up.`

I assume that you mean the `from_mag` with scale right?
