### ISSUE TITLE
Improve cubing of very large tiffs

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos-cuber#95]
For very large tiffs, the parallelism is bound by the available RAM. An effective pre-processing step might be to use imagemagick to create tiles for the tiffs (this isn't tied to the 32 buffer length of wkw). Then, use tiled cubing to increase parallelism while reducing RAM consumption.

Therefore, a first iteration for this could be a new wkcuber command which outputs tiled tiffs from untiled tiffs.

**Comment by normanrz** [comment]
Wouldn't the first step be to make cubing compatible with tiled tiffs?
Are you referring to [singe-file tiled tiffs](https://en.wikipedia.org/wiki/TIFF#Tiles) or multi-file tiff tiles?

**Comment by philippotto** [comment]
> Are you referring to [singe-file tiled tiffs](https://en.wikipedia.org/wiki/TIFF#Tiles) or multi-file tiff tiles?

I'm talking about "normal" single-file single-image tiffs without tiles. If you have tiff files with 30000**2 pixel, each procees needs ~ 60 GB RAM for peaks. This means, we can only have 2 processes for machines with 128 GB RAM.

If the tiffs were tiled into 4 files each, we could employ 8 processes for the same amount of RAM.

The tiling itself could be parallelized easily because we are not bound to the chunk size of 32.

**Comment by normanrz** [comment]
I think this is superseded by #272. do you agree @philippotto ?

**Comment by philippotto** [comment]
> I think this is superseded by #272. do you agree @philippotto ?

Yeah, I think, there might still be valid use cases for wkw where the input is huge and not 2D, but these cases are probably quite rare and I don't know of any current need for this. That's why, I'm closing this issue for now. #272 has a bigger impact. Feel free to reopen.
