### ISSUE TITLE
High-level dataset library

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos-cuber#99]
I would like to have a more high-level library for webknossos datasets. The library should have the following features

- [ ] Provide a handle for datasets (with multiple layers and mags)
- [ ] Property access to the datasets metadata
- [ ] Read/write data from specified layers and mags
- [ ] Provide a handle to a specified bounding box in the data
- [ ] The data handle should have methods for aligned chunking

As an example, this is code I'd like to write:
```python
from wkcuber import WKDataset

def work_on_chunk(slice):
  print("offset={} shape={}".format(slice.offset, slice.shape))

# Create handle
with WKDataset.open("/path/to/dataset") as ds:
  # Metadata access
  print("Color layer dtype={} bounding_box={}".format(ds["color"].dtype, ds["color"].bounding_box))
  
  # Write data
  ds["color"][Mag(2,2,1)][10:20, 10:20, 10:20] = np.zeros((10, 10, 10))

  # Create a data handle
  slice = ds["color"][Mag(2,2,1)].slice(offset=(10, 10, 10), size=(1024, 1024, 1024))

  # Read data from the data handle
  slice[0:10, 0:10, 0:10]

  # Chunking in the data handle
  with SlurmExecutor() as exec:
    slice.map_chunked(work_on_chunk, chunk_alignment=(32, 32, 32), executor=exec)
```

For this, I think we can re-use some code from the segmentation-tools. Notably the `BoundingBox` class and the `distribute.py`

Further extensions would be to also allow the manipulative steps from the wkcuber to this api. For example:
```python
ds["color"][Mag(1)].downsample(Mag(2, 2, 1), executor=exec)
ds["color"][Mag(2, 2, 1)].compress(executor=exec)
```

**Comment by philippotto** [comment]
Maybe this is a good issue for @rschwanhold? I think we should discuss/think through the new interface thoroughly before implementing it, since it will probably stick with us for quite some time.

**Comment by normanrz** [comment]
Makes sense. How would we spec that? I think it makes sense to have it in written form.

**Comment by philippotto** [comment]
> I think it makes sense to have it in written form.

Definitely. I think, we should write down all user-facing classes + method signatures.

**Comment by philippotto** [comment]
@rschwanhold Talk to me when you got capacities for this issue :)

Another interesting aspect for this is issue are tiff datasets for which we could define a dedicated format.
